=== jochenmanz/shopware-plugin-schemas/schema/config.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xsd:element name="config" type="config"/>

    <xsd:complexType name="config">
        <xsd:sequence minOccurs="0">
            <xsd:element name="elements"  type="elements"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="elements">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="element">
                <xsd:complexType>
                    <xsd:sequence maxOccurs="unbounded">
                        <xsd:element name="label"       type="label"  maxOccurs="unbounded" />
                        <xsd:element name="value"       type="xsd:string"/>
                        <xsd:element name="description" type="label"  maxOccurs="unbounded" />
                        <xsd:element name="store"       type="xsd:string" minOccurs="0"/>
                    </xsd:sequence>
                    <xsd:attribute name="type" type="type" default="text"/>
                    <xsd:attribute name="required" type="xsd:boolean" default="true"/>
                    <xsd:attribute name="scope" type="scope" default="local"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:choice>
    </xsd:complexType>

    <xsd:simpleType name="type">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="text"/>
            <xsd:enumeration value="textarea"/>
            <xsd:enumeration value="color"/>
            <xsd:enumeration value="date"/>
            <xsd:enumeration value="datetime"/>
            <xsd:enumeration value="time"/>
            <xsd:enumeration value="interval"/>
            <xsd:enumeration value="html"/>
            <xsd:enumeration value="mediaselection"/>
            <xsd:enumeration value="number"/>
            <xsd:enumeration value="select"/>
            <xsd:enumeration value="combo"/>
            <xsd:enumeration value="select"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="scope">
        <xsd:restriction base = "xsd:string">
            <xsd:enumeration value="local"/>
            <xsd:enumeration value="shop"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="description">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="lang" type="xsd:language" default="en"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="label">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="lang" type="xsd:language" default="en"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

</xsd:schema>

=== jochenmanz/shopware-plugin-schemas/tests/_files/config.xml
<?xml version="1.0" encoding="utf-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../schema/config.xsd">

    <elements>
        <element scope="local" required="true" type="text">
            <label lang="de">Mein textfeld</label>
            <label lang="en">My Textfield</label>
            <value>Some default value</value>
            <description lang="de">Meine Feld Beschreibung</description>
            <description lang="en">My Field description</description>
        </element>

        <element scope="local"  type="select">
            <label lang="de">Meine Selektion</label>
            <label lang="en">My Selection</label>
            <value>1</value>
            <description lang="de">Meine Feld Beschreibung</description>
            <description lang="en">My Field description</description>
            <store>
                <![CDATA[
array(
    array(1, 'Testvariable 1'),
    array(2, 'Testvariable 2'),
    array(3, 'Testvariable 3')
)
                ]]>
            </store>
        </element>
    </elements>
</config>
