=== jochenmanz/shopware-plugin-schemas/schema/menu.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xsd:element name="menu" type="menu"/>

    <xsd:complexType name="menu">
        <xsd:sequence minOccurs="0">
            <xsd:element name="entries"  type="entries"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="entries">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="entry">
                <xsd:complexType>
                    <xsd:sequence maxOccurs="unbounded">
                        <xsd:element name="label"      type="label"  maxOccurs="unbounded" />
                        <xsd:element name="controller" type="xsd:string"/>
                        <xsd:element name="action"     type="xsd:string"/>
                        <xsd:element name="class"      type="xsd:string" minOccurs="0"/>
                        <xsd:element name="parent"     type="parent"/>
                        <xsd:element name="active"     type="xsd:boolean"/>
                        <xsd:element name="position"   type="xsd:int"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="parent">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="identifiedBy" type="xsd:string" default="controller"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="label">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="lang" type="xsd:language" default="en"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

</xsd:schema>

=== jochenmanz/shopware-plugin-schemas/tests/_files/menu.xml
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../schema/menu.xsd">

    <entries>
        <entry>
            <label>SwagDefaultSort</label>
            <controller>SwagDefaultSort</controller>
            <action>index</action>
            <class>sprite-sort</class>
            <parent identifiedBy="label">Einstellungen</parent>
            <active>false</active>
            <position>-1</position>
        </entry>

        <entry>
            <label lang="en">SwagDefaultSort EN</label>
            <label lang="de">SwagDefaultSort DE</label>
            <controller>SwagDefaultSort</controller>
            <action>index</action>
            <class>sprite-sort</class>
            <parent identifiedBy="label">Einstellungen</parent>
            <active>false</active>
            <position>-1</position>
        </entry>
    </entries>
</menu>
